//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSWaveDistance.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PSWaveDistance.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        internal static byte[] PSWaveDistance {
            get {
                object obj = ResourceManager.GetObject("PSWaveDistance", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   [{&quot;Depth&quot;:0,&quot;TimeData&quot;:[{&quot;Seconds&quot;:0.1,&quot;PDist&quot;:0.481,&quot;SDist&quot;:0.284},{&quot;Seconds&quot;:0.2,&quot;PDist&quot;:0.962,&quot;SDist&quot;:0.569},{&quot;Seconds&quot;:0.3,&quot;PDist&quot;:1.442,&quot;SDist&quot;:0.853},{&quot;Seconds&quot;:0.4,&quot;PDist&quot;:1.923,&quot;SDist&quot;:1.138},{&quot;Seconds&quot;:0.5,&quot;PDist&quot;:2.405,&quot;SDist&quot;:1.422},{&quot;Seconds&quot;:0.6,&quot;PDist&quot;:2.887,&quot;SDist&quot;:1.707},{&quot;Seconds&quot;:0.7,&quot;PDist&quot;:3.369,&quot;SDist&quot;:1.991},{&quot;Seconds&quot;:0.8,&quot;PDist&quot;:3.851,&quot;SDist&quot;:2.277},{&quot;Seconds&quot;:0.9,&quot;PDist&quot;:4.335,&quot;SDist&quot;:2.563},{&quot;Seconds&quot;:1,&quot;PDist&quot;:4.82,&quot;SDist&quot;:2.849},{&quot;Seconds&quot;:1.1,&quot;PDist&quot;:5.306,&quot;SDist&quot;:3.134},{&quot;Secon [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string tjma2001_sec2dist {
            get {
                return ResourceManager.GetString("tjma2001-sec2dist", resourceCulture);
            }
        }
    }
}
